### ISSUE TITLE
Hi! How to get the s2_mean?

### ISSUE THREAD

**Issue by xufangchn** [cidcom/satellite-cloud-removal-dip#1]

**Comment by mikonvergence** [comment]
`s2_mean` represents the mean image with no cloud coverage acquired for the previous year in the experiments presented in our manuscript.

In general, any other signal with no clouds can be used in the place of `s2_mean` as long as it is spatially aligned with the cloudy image. For example, the last cloud-free sample could be used. As found in the paper, these types of images contain a very useful source of information for producing structurally consistent inpaintings.

**Comment by christation** [comment]
Closed due to inactivity, feel free to re-open.
