### ISSUE TITLE
Installing pip dependancies break Google Collab

### ISSUE THREAD

**Issue by christation** [cidcom/satellite-cloud-removal-dip#2]
The cell that installs packages in `01-Example-Use.ipynb` results on error:
```
ERROR: Cannot install torch==1.10.0, torchvision==0.10.0, torchvision==0.10.1, torchvision==0.11.2, torchvision==0.11.3, torchvision==0.12.0, torchvision==0.13.0, torchvision==0.13.1, torchvision==0.14.0, torchvision==0.14.1, torchvision==0.14.1+cu116, torchvision==0.5.0, torchvision==0.6.0, torchvision==0.6.1, torchvision==0.7.0, torchvision==0.8.0, torchvision==0.8.1, torchvision==0.8.2, torchvision==0.9.0 and torchvision==0.9.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[ ]

```

Changing the version of torch to `1.13.1` seems to solve the issues like the line below
```
!pip install -q torch==1.13.1 torchvision numpy rasterio==1.0.21 git+https://github.com/PyTorchLightning/pytorch-lightning
```

The issue seems to be caused by the fact that google collaborated has `touch` already installed 

```
import torch
torch.__version__
```

which returns `1.13.1+cu116`

**Comment by mikonvergence** [comment]
In the time of the first release of this repository, pytorch wouldn't be already installed on colab machines.

The repository still works with the newer versions of pytorch (`1.13.1` at the moment) and pytorch-related packages, so the installation line will be changed from:
```python
!pip install -q torch==1.13.1 torchvision numpy rasterio==1.0.21 git+https://github.com/PyTorchLightning/pytorch-lightning
```
to:
```python
!pip install -q rasterio pytorch-lightning
```

Also, another line in `LitDIP` will be fixed (the `on_pretrain_routine_end` becomes `on_fit_start`) to account for the new `pytorch-lightning` interface.

With these changes, the colab notebook has been run successfully!
