### ISSUE TITLE
How to get the s1_image?

### ISSUE THREAD

**Issue by AnnyZ08** [cidcom/satellite-cloud-removal-dip#4]
thanks in advance

**Comment by mikonvergence** [comment]
Hi @AnnyZ08!

 `s1_image` assumes that a Sentinel-1 SAR image is available. The use of S1 guidance is optional, but should be quite helpful.

This repository only provides a technique for inpainting the region of the optical image affected by a cloud. Sentinel data can be acquired in various ways, so it depends on your use case.
