### ISSUE TITLE
runtime error - different tensor size

### ISSUE THREAD

**Issue by AnnyZ08** [cidcom/satellite-cloud-removal-dip#5]
Hi, I tried running your Example-Use-colab.ipynb with the pictures you provided and it went successfully. Then, I tried using my own picture(same dataset, just different input image), and I encountered the following runtime error. 
"RuntimeError: The size of tensor a (832) must match the size of tensor b (800) at non-singleton dimension 3"
All the input image have size (800,800), so I am not sure why this is happening. I also tried with different input images that also have the same size, and the same error occured. 

Details:
- I input two images: s2_image and mask, they have the same size
- mask.shape = (800,800)
- s2_image.shape = (800,800,3)

Full error message:

C:\Users\VIS3\satellite-cloud-removal-dip-main\src\LitDIP.py:172: UserWarning: Using a target size (torch.Size([1, 3, 800, 800])) that is different to the input size (torch.Size([1, 3, 832, 832])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = F.mse_loss(output, target, reduction = 'none')

RuntimeError                              Traceback (most recent call last)
Cell In[23], line 6
      1 trainer = pl.Trainer(
      2     max_epochs = 4,            
      3     logger=False,
      4     accelerator = 'auto'
      5 )
----> 6 trainer.fit(my_model)

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:582, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    580     raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.__class__.__qualname__}")
    581 self.strategy._lightning_module = model
--> 582 call._call_and_handle_interrupt(
    583     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    584 )

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\call.py:38, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     36         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     37     else:
---> 38         return trainer_fn(*args, **kwargs)
     40 except _TunerExitException:
     41     trainer._call_teardown_hook()

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:624, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    617 ckpt_path = ckpt_path or self.resume_from_checkpoint
    618 self._ckpt_path = self._checkpoint_connector._set_ckpt_path(
    619     self.state.fn,
    620     ckpt_path,  # type: ignore[arg-type]
    621     model_provided=True,
    622     model_connected=self.lightning_module is not None,
    623 )
--> 624 self._run(model, ckpt_path=self.ckpt_path)
    626 assert self.state.stopped
    627 self.training = False

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:1061, in Trainer._run(self, model, ckpt_path)
   1057 self._checkpoint_connector.restore_training_state()
   1059 self._checkpoint_connector.resume_end()
-> 1061 results = self._run_stage()
   1063 log.detail(f"{self.__class__.__name__}: trainer tearing down")
   1064 self._teardown()

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:1140, in Trainer._run_stage(self)
   1138 if self.predicting:
   1139     return self._run_predict()
-> 1140 self._run_train()

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:1163, in Trainer._run_train(self)
   1160 self.fit_loop.trainer = self
   1162 with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1163     self.fit_loop.run()

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\fit_loop.py:267, in FitLoop.advance(self)
    265 self._data_fetcher.setup(dataloader, batch_to_device=batch_to_device)
    266 with self.trainer.profiler.profile("run_training_epoch"):
--> 267     self._outputs = self.epoch_loop.run(self._data_fetcher)

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py:214, in TrainingEpochLoop.advance(self, data_fetcher)
    211     self.batch_progress.increment_started()
    213     with self.trainer.profiler.profile("run_training_batch"):
--> 214         batch_output = self.batch_loop.run(kwargs)
    216 self.batch_progress.increment_processed()
    218 # update non-plateau LR schedulers
    219 # update epoch-interval ones only when we are at the end of training epoch

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py:88, in TrainingBatchLoop.advance(self, kwargs)
     84 if self.trainer.lightning_module.automatic_optimization:
     85     optimizers = _get_active_optimizers(
     86         self.trainer.optimizers, self.trainer.optimizer_frequencies, kwargs.get("batch_idx", 0)
     87     )
---> 88     outputs = self.optimizer_loop.run(optimizers, kwargs)
     89 else:
     90     outputs = self.manual_loop.run(kwargs)

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:200, in OptimizerLoop.advance(self, optimizers, kwargs)
    197 def advance(self, optimizers: List[Tuple[int, Optimizer]], kwargs: OrderedDict) -> None:
    198     kwargs = self._build_kwargs(kwargs, self.optimizer_idx, self._hiddens)
--> 200     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
    201     if result.loss is not None:
    202         # automatic optimization assumes a loss needs to be returned for extras to be considered as the batch
    203         # would be skipped otherwise
    204         self._outputs[self.optimizer_idx] = result.asdict()

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:247, in OptimizerLoop._run_optimization(self, kwargs, optimizer)
    239         closure()
    241 # ------------------------------
    242 # BACKWARD PASS
    243 # ------------------------------
    244 # gradient update with accumulated gradients
    245 else:
    246     # the `batch_idx` is optional with inter-batch parallelism
--> 247     self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
    249 result = closure.consume_result()
    251 if result.loss is not None:
    252     # if no result, user decided to skip optimization
    253     # otherwise update running loss + reset accumulated loss
    254     # TODO: find proper way to handle updating running loss

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:357, in OptimizerLoop._optimizer_step(self, optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
    354     self.optim_progress.optimizer.step.increment_ready()
    356 # model hook
--> 357 self.trainer._call_lightning_module_hook(
    358     "optimizer_step",
    359     self.trainer.current_epoch,
    360     batch_idx,
    361     optimizer,
    362     opt_idx,
    363     train_step_and_backward_closure,
    364     on_tpu=isinstance(self.trainer.accelerator, TPUAccelerator),
    365     using_native_amp=(self.trainer.amp_backend == AMPType.NATIVE),
    366     using_lbfgs=is_lbfgs,
    367 )
    369 if not should_accumulate:
    370     self.optim_progress.optimizer.step.increment_completed()

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:1305, in Trainer._call_lightning_module_hook(self, hook_name, pl_module, *args, **kwargs)
   1302 pl_module._current_fx_name = hook_name
   1304 with self.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{hook_name}"):
-> 1305     output = fn(*args, **kwargs)
   1307 # restore current_fx when nested context
   1308 pl_module._current_fx_name = prev_fx_name

File ~\miniconda3\lib\site-packages\pytorch_lightning\core\module.py:1661, in LightningModule.optimizer_step(self, epoch, batch_idx, optimizer, optimizer_idx, optimizer_closure, on_tpu, using_native_amp, using_lbfgs)
   1579 def optimizer_step(
   1580     self,
   1581     epoch: int,
   (...)
   1588     using_lbfgs: bool = False,
   1589 ) -> None:
   1590     r"""
   1591     Override this method to adjust the default way the :class:`~pytorch_lightning.trainer.trainer.Trainer` calls
   1592     each optimizer.
   (...)
   1659 
   1660     """
-> 1661     optimizer.step(closure=optimizer_closure)

File ~\miniconda3\lib\site-packages\pytorch_lightning\core\optimizer.py:169, in LightningOptimizer.step(self, closure, **kwargs)
    166     raise MisconfigurationException("When `optimizer.step(closure)` is called, the closure should be callable")
    168 assert self._strategy is not None
--> 169 step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
    171 self._on_after_step()
    173 return step_output

File ~\miniconda3\lib\site-packages\pytorch_lightning\strategies\strategy.py:234, in Strategy.optimizer_step(self, optimizer, opt_idx, closure, model, **kwargs)
    232 # TODO(lite): remove assertion once strategy's optimizer_step typing is fixed
    233 assert isinstance(model, pl.LightningModule)
--> 234 return self.precision_plugin.optimizer_step(
    235     optimizer, model=model, optimizer_idx=opt_idx, closure=closure, **kwargs
    236 )

File ~\miniconda3\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py:121, in PrecisionPlugin.optimizer_step(self, optimizer, model, optimizer_idx, closure, **kwargs)
    119 """Hook to run the optimizer step."""
    120 closure = partial(self._wrap_closure, model, optimizer, optimizer_idx, closure)
--> 121 return optimizer.step(closure=closure, **kwargs)

File ~\miniconda3\lib\site-packages\torch\optim\optimizer.py:280, in Optimizer.profile_hook_step.<locals>.wrapper(*args, **kwargs)
    276         else:
    277             raise RuntimeError(f"{func} must return None or a tuple of (new_args, new_kwargs),"
    278                                f"but got {result}.")
--> 280 out = func(*args, **kwargs)
    281 self._optimizer_step_code()
    283 # call optimizer step post hooks

File ~\miniconda3\lib\site-packages\torch\optim\optimizer.py:33, in _use_grad_for_differentiable.<locals>._use_grad(self, *args, **kwargs)
     31 try:
     32     torch.set_grad_enabled(self.defaults['differentiable'])
---> 33     ret = func(self, *args, **kwargs)
     34 finally:
     35     torch.set_grad_enabled(prev_grad)

File ~\miniconda3\lib\site-packages\torch\optim\adam.py:121, in Adam.step(self, closure)
    119 if closure is not None:
    120     with torch.enable_grad():
--> 121         loss = closure()
    123 for group in self.param_groups:
    124     params_with_grad = []

File ~\miniconda3\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py:107, in PrecisionPlugin._wrap_closure(self, model, optimizer, optimizer_idx, closure)
     94 def _wrap_closure(
     95     self,
     96     model: "pl.LightningModule",
   (...)
     99     closure: Callable[[], Any],
    100 ) -> Any:
    101     """This double-closure allows makes sure the ``closure`` is executed before the
    102     ``on_before_optimizer_step`` hook is called.
    103 
    104     The closure (generally) runs ``backward`` so this allows inspecting gradients in this hook. This structure is
    105     consistent with the ``PrecisionPlugin`` subclasses that cannot pass ``optimizer.step(closure)`` directly.
    106     """
--> 107     closure_result = closure()
    108     self._after_closure(model, optimizer, optimizer_idx)
    109     return closure_result

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:147, in Closure.__call__(self, *args, **kwargs)
    146 def __call__(self, *args: Any, **kwargs: Any) -> Optional[Tensor]:
--> 147     self._result = self.closure(*args, **kwargs)
    148     return self._result.loss

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:133, in Closure.closure(self, *args, **kwargs)
    132 def closure(self, *args: Any, **kwargs: Any) -> ClosureResult:
--> 133     step_output = self._step_fn()
    135     if step_output.closure_loss is None:
    136         self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")

File ~\miniconda3\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:406, in OptimizerLoop._training_step(self, kwargs)
    397 """Performs the actual train step with the tied hooks.
    398 
    399 Args:
   (...)
    403     A ``ClosureResult`` containing the training step output.
    404 """
    405 # manually capture logged metrics
--> 406 training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
    407 self.trainer.strategy.post_training_step()
    409 model_output = self.trainer._call_lightning_module_hook("training_step_end", training_step_output)

File ~\miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py:1443, in Trainer._call_strategy_hook(self, hook_name, *args, **kwargs)
   1440     return
   1442 with self.profiler.profile(f"[Strategy]{self.strategy.__class__.__name__}.{hook_name}"):
-> 1443     output = fn(*args, **kwargs)
   1445 # restore current_fx when nested context
   1446 pl_module._current_fx_name = prev_fx_name

File ~\miniconda3\lib\site-packages\pytorch_lightning\strategies\strategy.py:378, in Strategy.training_step(self, *args, **kwargs)
    376 with self.precision_plugin.train_step_context():
    377     assert isinstance(self.model, TrainingStep)
--> 378     return self.model.training_step(*args, **kwargs)

File ~\satellite-cloud-removal-dip-main\src\LitDIP.py:192, in LitDIP.training_step(self, batch, batch_idx)
    188     input = self.input
    190 out = self.forward(input)
--> 192 return self.get_loss(out, self.target, self.mask)

File ~\satellite-cloud-removal-dip-main\src\LitDIP.py:172, in LitDIP.get_loss(self, output, target, mask)
    170 def get_loss(self, output, target, mask = None):
--> 172     loss = F.mse_loss(output, target, reduction = 'none')
    174     if mask is not None:
    175         loss = loss[mask]

File ~\miniconda3\lib\site-packages\torch\nn\functional.py:3294, in mse_loss(input, target, size_average, reduce, reduction)
   3291 if size_average is not None or reduce is not None:
   3292     reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 3294 expanded_input, expanded_target = torch.broadcast_tensors(input, target)
   3295 return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))

File ~\miniconda3\lib\site-packages\torch\functional.py:74, in broadcast_tensors(*tensors)
     72 if has_torch_function(tensors):
     73     return handle_torch_function(broadcast_tensors, tensors, *tensors)
---> 74 return _VF.broadcast_tensors(tensors)

RuntimeError: The size of tensor a (832) must match the size of tensor b (800) at non-singleton dimension 3

**Comment by AnnyZ08** [comment]
I converted the image size to 256*256 and the problem solved.

**Comment by mikonvergence** [comment]
Hi @AnnyZ08. Yes, the network does not support just about any image shape, due to the internal downsampling and upsampling convolutions - it will generally work quite well for heights and widths being the power of 2.

There are a few ways to get around this, such as padding the original image (and excluding padded pixels from the mask) or applying interpolation to the network output before computing the loss.
