### ISSUE TITLE
after s2_preprocess, s2_image color is distorted

### ISSUE THREAD

**Issue by AnnyZ08** [cidcom/satellite-cloud-removal-dip#6]
Hi! I tried to run your code with my own image, however, after the I run "s2_image = s2_preprocess('./cloud_test_final.tif')", the color of the input image became very dark. Left is the original image, right is the image after s2_preprocess. I was wondering is there anyway to fix this? Thanks in advance!
![image](https://github.com/strath-ai/satellite-cloud-removal-dip/assets/97325065/b207602a-2bc2-4e16-8d6b-f5fe63f8045f)

**Comment by mikonvergence** [comment]
As can be seen in the [source code](https://github.com/strath-ai/satellite-cloud-removal-dip/blob/main/src/utils.py), `s2_preprocess` is a function for preprocessing a .tif with Sentinel-2 data, so the applied scale might not work for other sources.

You do not need to use this function and instead can supply your own input, as long as it has the correct order of dimensions.
