### ISSUE TITLE
About how to prepare test data

### ISSUE THREAD

**Issue by huangjingyuan7** [cidcom/satellite-cloud-removal-dip#7]
Hello, I would like to inquire about how to choose the frequency band for testing data, such as Sentinel(red,green,swir), and how to make mask.npy？or mask.npy?
Since I am a beginner, these questions seem silly, thank you very much！

**Comment by mikonvergence** [comment]
Hello @huangjingyuan7!

I am not sure if I understand the questions, so if I missed something, please let me know:

* The tool in this repo can work with many formatting approaches, you can use a 3-channel RGB image (Sentinel-2 or not) or you can use any subset of multi-spectral data, In my case, I often use other sources of data to help with reconstructing structure, for example historical sample or Sentinel-1 SAR sample (more detail in the related paper: https://www.mdpi.com/2072-4292/14/6/1342).
* The tool does not perform masking and instead requires a mask to be supplied. For example, if you're interested in the task of cloud removal, you can use a standard cloud detection tool to use as a mask for your image.
