### ISSUE TITLE
can you provide pretrained checkpoints

### ISSUE THREAD

**Issue by SushilGhildiyal143** [cidcom/satellite-cloud-removal-dip#8]

**Comment by mikonvergence** [comment]
This method does not involve pretrained checkpoints. It uses an internal optimization procedure, which is performed from scratch (and takes a few minutes to complete).

You can read more details about how it works in the related paper:
https://www.mdpi.com/2072-4292/14/6/1342

and you can test it online in an interactive notebook on Google colab:
https://colab.research.google.com/github/cidcom/satellite-cloud-removal-dip/blob/main/01-Example-Use-colab.ipynb
